name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
      # - name: Copy repository files
      #   uses: actions/checkout@v5
 
      # - name: Install Python
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: '3.13'
      
      # - name: Install Poetry
      #   run: pipx install poetry

      - name: Disable Poetry Keyring
        run: poetry config keyring.enabled false

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run task test

    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
